name: Environment Secret Test
on:
  workflow_dispatch:

jobs:
  Environment:
    name: Pull_request Info
    runs-on: ubuntu-latest
    steps:
      - name: PR Info
        run: |
          echo "secrets = ${{secrets}}"
          echo "TOKEN=${{ secrets.ACTION_TOKEN }}"
      - name: Get issues
        run: |
          token=${{ secrets.ACTION_TOKEN }}
          issues=$(curl -s -H "Authorization: token $token" https://api.github.com/repos/Rosyrain/github_action_test/issues )
          if [[ $(echo $issues | jq 'length') -gt 0 ]]; then
            echo "Token is likely valid as issues were retrieved."
          else
            echo "Token might be invalid as no issues were retrieved."
          fi
  CI_test:
    name: CI_test secrets
    uses: Rosyrain/CI_test/.github/workflows/environment_secrets_test.yaml@main
    secrets: inherit