name: Environment Secret Test
on:
  workflow_dispatch:

jobs:
  Environment:
    name: Pull_request Info
    runs-on: ubuntu-latest
    steps:
      - name: PR Info
        run: |
          echo "secrets = ${{secrets}}"
          echo "secrets.GITHUB_TOKEN=${{ secrets.ACTION_TOKEN }}"
      - shell: bash
        env:
          ACTION_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          echo "$ACTION_TOKEN"

  CI_test:
    name: CI_test secrets
    uses: Rosyrain/CI_test/.github/workflows/environment_secrets_test.yaml@main
    secrets: inherit