name: Environment Secret Test
on:
  workflow_dispatch:

jobs:
  Environment:
    name: Pull_request Info
    runs-on: ubuntu-latest
    steps:
      - name: PR Info
        run: |
          echo "secrets.GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"

  CI_test:
    name: CI_test secrets
    uses: Rosyrain/CI_test/.github/workflow/environment_secrets_test.yaml@main
    secrets: inherit