name: Public repo Use Private repo workflow
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: ACTION
    steps:
    - uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.TOKEN_ACTION }}
        repository: Rosyrain/CI_test
        secrets: inherit
        event-type: test
        client-payload: '{}'