name: Public repo Use Private repo workflow
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: ACTION
    outputs:
      workflow: ${{ steps.s2.outputs.workflow }}
    steps:
    - name: Get issues
      run: |
        token=${{ secrets.TOKEN_ACTION }}
        issues=$(curl -L -s -H "Authorization: Bearer $token" https://api.github.com/repos/Rosyrain/github_action_test/issues/1 )
        if [[ $(echo $issues | jq 'length') -gt 0 ]]; then
          echo "$issues"
        else
          echo "Token might be invalid as no issues were retrieved."
        fi
  checkout-private-workflow:
    runs-on: ubuntu-latest
    environment: ACTION
    steps:
      - name: checkout-private-repo
        uses: checkout-action@v4
        with:
          repo: Rosyrain/CI_test
          ref: main
          path: ./CI
      - name: Output workflow yaml
        id: s2
        run: |
          echo "workflow=$(cat ./CI/.github/workflows/environment_secrets_test.yaml)" >> $GITHUB_OUTPUT

  uses-private-workflow:
    needs: [checkout-private-workflow]
    runs-on: ubuntu-latest
    steps:
      - name: Get Workflow
        run: |
          cd $GITHUB_WORKSPACE
          echo "${{ needs.checkout-private-workflow.outputs.workflow }}" >> workflow.yaml
      - uses: ${{ github.workspace }}/workflow.yaml