name: Binary Test and Release

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  binary_test:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.valgrind_test.outcome == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go Env
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Build Go
        run: go build -o main.exe

      - name: Test Go
        run: go test -v ./...

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Run tests with Valgrind
        id: valgrind_test
        run: |
          valgrind --leak-check=full --error-exitcode=1 ./main.exe
          echo "::set-output name=should_release::false"

  release:
    needs: [binary_test]
    if: needs.binary_test.outputs.should_release == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            V0.0.1
          draft: false
          prerelease: false