name: Remove Labels

on:
  issues:
    types: [assigned]

jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ github.event.assignee.login != 'matrx-meow' }}
    steps:
      - name: Remove Labels
        uses: Rosyrain/CI_test/actions/rm-labels@main
        id: step1
        env:
          BASE_URL: ${{ github.api_url }}
        with:
          repository: ${{ github.repository }}  # 获取执行该作业的仓库名 形如: matrixorigin/CI
          issue_number: ${{ github.event.issue.number }}  # 获取当前操作的issue number
          github_token: ${{ secrets.TOKEN_ACTION }}  # 获取github action token操作权限
          labels: 'needs-triage'  #相关自定义label配置 形如 label1,label2
      - name: WeChat Work notification
        if: ${{ steps.step1.outputs.result == 'yes' }}
        id: notification
        run: |
          echo "assigned to ${{ github.event.assignee.login }}"
          echo "delete label success... ..."