name: Template Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Start time
        id: job_start
        run: |
          # 设置时区为上海时区
          export TZ='Asia/Shanghai'
          
          # 原始的 UTC 时间
          #utcTime="2024-11-15T08:33:52Z"
          action_time=${{ github.pull_requests.head.repo.pushed_at }}
          
          # 转换为上海时区并格式化
          # 使用 date 命令和 +%Y-%m-%d\ %H:%M:%S 格式字符串
          
          # 使用 %z 来获取原始时间的时区偏移，然后手动调整为上海时区
          ACTiON_TIME=$(date -d "${action_time}" '+%Y-%m-%d %H:%M:%S')
          
          # 打印结果
          echo "ACTION_TIME=${ACTION_TIME}" >> $GITHUB_OUTPUT

          # 获取格式化的日期时间字符串
          time=$(date '+%Y-%m-%d %H:%M:%S')

          echo "START_TIME=${time}" >> $GITHUB_OUTPUT
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "ACTION_TIME=${{ steps.job_start.outputs.ACTION_TIME }}"
          echo  "START_TIME=${{ steps.job_start.outputs.START_TIME }}"
          echo "======================================================="
          echo "$GITHUB_CONTEXT"
          echo "======================================================="
          
          echo "action_time=${{ github.action_time }}"
