name: Template Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Start time
        id: job_start
        run: |
          # 设置时区为上海时区
          export TZ='Asia/Shanghai'

          # 获取格式化的日期时间字符串
          time=$(date '+%Y-%m-%d %H:%M:%S')

          echo "START_TIME=${time}" >> $GITHUB_OUTPUT
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo  ${{ steps.job_start.outputs.START_TIME }}
          echo "======================================================="
          echo "$GITHUB_CONTEXT"
          echo "======================================================="
          echo "action_time=${{ github.action_time }}"