name: Template Test
on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "$GITHUB_CONTEXT"
          echo "======================================================="
          echo "action_time=${{ github.run_started_at }}"