name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo info
        run: echo "This job should be exec"
  skip-job:
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      run: echo "This job should be skipped"